### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by Dovernh** [sajivkumar/mathjax-angular#10]
Your example shows:

imports: [
    MathJaxModule.forRoot(/*Optional Config*/)
  ],

Thee import:
import { MathjaxModule } from 'mathjax-angular';

Notice the case if "J". I believe it should be a lowercase j, that's what worked for me.

**Comment by codeaye** [comment]
Sorry, That was a typo from our side, It should be fixed now.

Thanks for letting us know.

**Comment by pschaub** [comment]
I think it's not solved yet. I still see wrong code examples on GitHub (branch "readme" not merged yet?) and npmjs.
For npmjs see https://github.com/sajivkumar/mathjax-angular/issues/15
