### ISSUE TITLE
Can't bind to 'mathjax' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by Dovernh** [sajivkumar/mathjax-angular#11]
I'm getting this error in the vscode editor
![image](https://user-images.githubusercontent.com/1800249/127010439-efda4266-4528-450f-ab4d-a2d23bda1968.png)

**Comment by codeaye** [comment]
I think this was caused due to a typo in the readme as you have identified in your previous submitted issue. It should be fixed now.
