### ISSUE TITLE
Typos in code examples on npmjs

### ISSUE THREAD

**Issue by pschaub** [sajivkumar/mathjax-angular#15]
The description on npmjs contains multiple typos in the code example.

Wrong:
```import { MathJaxModule } from 'mathjax-angular';```
Correct:
```import { MathjaxModule } from 'mathjax-angular';```

Wrong:
```MathJaxModule.forRoot(/*Optional Config*/)```
Correct:
```MathjaxModule.forRoot(/*Optional Config*/)```

Wrong:
```MathJaxModule.forChild()```
Correct:
```MathjaxModule.forChild()```

See https://www.npmjs.com/package/mathjax-angular

**Comment by NavTheSass** [comment]
It seems that we had already fixed these typos but forgot to merge the fixed version. @sajivkumar
