### ISSUE TITLE
Support for MathJax 2

### ISSUE THREAD

**Issue by pschaub** [sajivkumar/mathjax-angular#16]
It would be great to have support for [MathJax 2](https://docs.mathjax.org/en/v2.7-latest/start.html) because some features are [not yet available in MathJax 3](https://docs.mathjax.org/en/latest/upgrading/v2.html#v2-not-ported).

**Comment by sajivkumarvelayudhan** [comment]
Not planning to support any earlier versions as v3 is a complete re-write.
https://docs.mathjax.org/en/latest/upgrading/v2.html

**Comment by codeaye** [comment]
This library is specifically designed for Matjax 3, so we are not planning to support any earlier versions.
