### ISSUE TITLE
update to angular 13

### ISSUE THREAD

**Issue by rubenlagatie** [sajivkumar/mathjax-angular#19]
Hi sajivkumar,

Would it be possible to update the package to angular 13. We get a dependency tree error when installing this package in an angular 13 project because this package has a peerDepedency on angular 12.

Thanks for the great package!

**Comment by mauler2025** [comment]
You can do `npm install mathjax-angular --force`.

**Comment by sajivkumar** [comment]
We have now upgraded to Angular 14 @ https://github.com/sajivkumar/mathjax-angular/pull/22
Thanks for your support
