### ISSUE TITLE
 Function calls are not supported in decorators but 'MathjaxModule' was called.

### ISSUE THREAD

**Issue by peipeihan2023** [sajivkumar/mathjax-angular#28]

**Comment by sajivkumar** [comment]
can you described it with an example please

**Comment by mratanusarkar** [comment]
@peipeihan2023 this feels like some line from runtime error. Could you please provide some more details and maybe the 
- whole error stack 
- with how to replicate the same by some example code 
- or sharing scenarios where this occures?

**Comment by sajivkumar** [comment]
no response once on error details
